// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeh7zSS6cnmqus0AW5zZR0raC0J-Qa_t4',
    appId: '1:172978654185:web:08eb9cdb97d2d9da55d978',
    messagingSenderId: '172978654185',
    projectId: 'main-1f45a',
    authDomain: 'main-1f45a.firebaseapp.com',
    databaseURL: 'https://main-1f45a-default-rtdb.firebaseio.com',
    storageBucket: 'main-1f45a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu5p1Ln1ARU_l78BVW8IBtRhGh6l1xrns',
    appId: '1:172978654185:android:451c4a5c5098873755d978',
    messagingSenderId: '172978654185',
    projectId: 'main-1f45a',
    databaseURL: 'https://main-1f45a-default-rtdb.firebaseio.com',
    storageBucket: 'main-1f45a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsNQLigSR3ifIPh4DkSF5EU8UWj37yOss',
    appId: '1:172978654185:ios:457313cfc2755dd055d978',
    messagingSenderId: '172978654185',
    projectId: 'main-1f45a',
    databaseURL: 'https://main-1f45a-default-rtdb.firebaseio.com',
    storageBucket: 'main-1f45a.appspot.com',
    androidClientId: '172978654185-2p8jtemjuqkmif9fbr95jdvgj4jmek63.apps.googleusercontent.com',
    iosClientId: '172978654185-q8b3b700mepj4prbhj3euh8ipcejt6ns.apps.googleusercontent.com',
    iosBundleId: 'com.example.dateAppTeam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsNQLigSR3ifIPh4DkSF5EU8UWj37yOss',
    appId: '1:172978654185:ios:457313cfc2755dd055d978',
    messagingSenderId: '172978654185',
    projectId: 'main-1f45a',
    databaseURL: 'https://main-1f45a-default-rtdb.firebaseio.com',
    storageBucket: 'main-1f45a.appspot.com',
    androidClientId: '172978654185-7mqh9sn5gb8054q3eg2cdie6qudc9e0b.apps.googleusercontent.com',
    iosClientId: '172978654185-q8b3b700mepj4prbhj3euh8ipcejt6ns.apps.googleusercontent.com',
    iosBundleId: 'com.example.dateAppTeam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeh7zSS6cnmqus0AW5zZR0raC0J-Qa_t4',
    appId: '1:172978654185:web:af582fb459466e0c55d978',
    messagingSenderId: '172978654185',
    projectId: 'main-1f45a',
    authDomain: 'main-1f45a.firebaseapp.com',
    databaseURL: 'https://main-1f45a-default-rtdb.firebaseio.com',
    storageBucket: 'main-1f45a.appspot.com',
  );

}